config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :feeds

  root to: 'static#index'

  get '/bangumi', to: 'bgm#index', as: 'bangumi_index'
  get '/bangumi/timeline', to: 'bgm#timeline', as: 'bangumi_timeline'
  get '/bangumi/:id', to: 'bgm#bangumi', as: 'bangumi_show'
  get '/ep/:id', to: 'bgm#play', as: 'bangumi_play'
  get '/cover/:id', to: 'bgm#cover', as: 'bangumi_cover'


  get '/tasks', to: 'cron_task#index', as: 'cron_task_index'
  get '/tasks/:name/enqueue', to: 'cron_task#enqueue', as: 'cron_task_enqueue'
  get '/tasks/:name/toggle', to: 'cron_task#toggle', as: 'cron_task_toggle'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bgm_controller.rb
class BgmController < ApplicationController

  def index
    @bgms = Feed.all
  end

  def timeline
    @bgms = Feed.where(:is_finished => false)
  end

  def bangumi
    @feed = Feed.find(params[:id])
  end

  def play
    @item = Item.find(params[:id])

    stat_str = StatCache::RedisCache::Redis.get("item_#{@item.id}_status")
    @status = {}
    @status["uploadedEver"] = 0
    @status["downloadedEver"] = 0

    if !stat_str.nil? then
      @status = Marshal.load(StatCache::RedisCache::Redis.get("item_#{@item.id}_status"))
    end
  end

  def cover
    feed = Feed.find(params[:id])
    send_data feed.cover, type: feed.cover_type
  end
end

app/controllers/cron_task_controller.rb
class CronTaskController < ApplicationController
    def index
        @server = Sidekiq::server?
        @tasks = Sidekiq::Cron::Job.all
    end

    def toggle
        job = Sidekiq::Cron::Job.find :name => params[:name]
        if job.status == 'enabled' then
          job.disable!
        else
          job.enable!
        end
        redirect_to action: "index"
    end

    def enqueue
        job = Sidekiq::Cron::Job.find :name => params[:name]
        job.enque!
        redirect_to action: "index"
    end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    if (params[:show_finished] == "true") then
      session[:hide_finished_feeds] = false
    elsif (params[:show_finished] == "false") then
      session[:hide_finished_feeds] = true
    end
    if (session[:hide_finished_feeds]) then
      @feeds = Feed.where(:is_finished => false).order_by(:created_at => :desc)
    else
      @feeds = Feed.all
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    if feed_params[:cover] then
      @feed.cover_type = feed_params[:cover].content_type
      @feed.cover = feed_params[:cover].read
    end
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      @feed.update(feed_params)
      if feed_params[:cover] then
        @feed.cover_type = feed_params[:cover].content_type
        @feed.cover = feed_params[:cover].read
      end
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.fetch(:feed, {}).permit(:name, :url, :cover, :offset, :is_finished, :total_ep_count, :auto_finish)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @status = Marshal.load(StatCache::RedisCache::Redis.get("item_#{@item.id}_status"))
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    if !(@item.status == 'DELETED' || @item.status == 'PENDING_DELETE') 
      @item.status = 'PENDING_DELETE'
      @item.save
    else
      @item.destroy
    end
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.fetch(:item, {})
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bgm_helper.rb
module BgmHelper
end

app/helpers/cron_task_helper.rb
module CronTaskHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/bgm/_card.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= item.name %>
      <% est = (DateTime.now.to_date - item.last_updated.to_date).to_i %>
      <a class="btn <%= if est > 7 then "btn-warning" else "btn-info" end %> btn-xs pull-right" data-toggle="tooltip" title="" data-placement="top" data-original-title="<%= item.last_updated %>">
        <%= fa_icon "clock-o" %> <%= est %> <%= if est > 1 then "days" else "day" end %>
      </a>
    </h3>
  </div>
  <div class="panel-body">
    <a href="<%= url_for bangumi_show_path(item) %>" class="thumbnail">
      <%= image_tag bangumi_cover_url(item) %>
    </a>
    <p><span class="label label-info"><%= "#{item.amount} / #{item.total_ep_count}" %></span></p>
    <div class="progress">
      <div class="progress-bar progress-bar-info" style="width: <%= "#{(item.amount.to_f / item.total_ep_count.to_f)*100.0}%" %>"></div>
    </div>
    <div class="btn-group">
      <% i = item.items.sort_by {| obj | obj.ep_id }.reverse %>
      <%= link_to "#{fa_icon "play"} EP ##{i.first.ep_id} #{case i.first.status when "DOWNLOADING" then fa_icon "download" when "SLICING" then fa_icon "bolt" when "PENDING_SLICE" then fa_icon "bolt" end}".html_safe, bangumi_play_path(i.first), class: "btn btn-sm #{if i.first.status != 'AVAILABLE' then 'btn-warning' else 'btn-success' end}"%>
      <% i.delete(i.first) %>
      <div class="btn-group">
        <a class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
          <%= fa_icon "history" %>&nbsp;
          <%= fa_icon "caret-down" %>
        </a>
        <ul class="dropdown-menu">
          <% i.each do | ep | %>
          <li><%= link_to "EP ##{ep.ep_id} #{case ep.status when "DOWNLOADING" then fa_icon "download" when "SLICING" then fa_icon "bolt" when "PENDING_SLICE" then fa_icon "bolt" end}".html_safe, bangumi_play_path(ep.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/bgm/_ep_list.html.erb
<div class="list-group">
  <% item.feed.items.sort_by {| obj | obj.ep_id }.each do | ep | %>
  <a href="<%= url_for(bangumi_play_path(ep.id)) %>" class="list-group-item <%= if ep.id == item.id then 'active' end %>">
    <h4 class="list-group-item-heading"><%= if ep.id == item.id then fa_icon 'play' end %> EP #<%= ep.ep_id %> <%= " #{case ep.status when "DOWNLOADING" then fa_icon "download" when "SLICING" then fa_icon "bolt" when "PENDING_SLICE" then fa_icon "bolt" end}".html_safe %></h4>
    <p class="list-group-item-text"><%= ep.name %></p>
  </a>
  <% end %>
</div>

app/views/bgm/_status_list.erb
<ul class="list-group">
  <li class="list-group-item">
    <span class="badge"><%= Filesize.from("#{status["uploadedEver"]}B").pretty %></span>
    <%= fa_icon "upload" %> Uploaded
  </li>
  <li class="list-group-item">
    <span class="badge"><%= Filesize.from("#{status["downloadedEver"]}B").pretty %></span>
    <%= fa_icon "download" %> Downloaded
  </li>
</ul>

app/views/bgm/bangumi.html.erb
<%= @feed.inspect %>

app/views/bgm/index.html.erb
<% bgms = @bgms.to_a.delete_if {| obj | obj.last_updated == nil}.sort_by {| obj | obj.last_updated.to_date }.reverse %>
<div class="row-fluid">
  <% bgms.each do | bgm | %>
    <div class="col-xs-12 col-sm-3">
      <%= render partial: 'card', locals: {item: bgm} %>
    </div>
  <% end %>
</div>

app/views/bgm/play.html.erb
<div class="row">
  <div class="col-xs-12 col-md-9">
    <div class="embed-responsive embed-responsive-16by9">
      <video id="my-video" class="video-js embed-responsive-item" controls preload="auto" data-setup="{}">
      <source src="/hls/<%= @item.id %>.m3u8" type='application/x-mpegURL'>
        <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
      </video>
    </div>
  </div>
  <div class="col-xs-12 col-md-3">
    <%= render partial: 'ep_list', locals: {item: @item} %>
  </div>
  <div class="col-xs-12 col-md-3">
    <%= render partial: 'status_list', locals: {status: @status} %>
  </div>
  <div class="col-xs-12 col-md-3">
    <%= link_to fa_icon('external-link') + ' Local Player', "/hls/#{@item.id}.m3u8", class: "btn btn-info" %>
  </div>
</div>

app/views/bgm/timeline.html.erb
<% bgms = @bgms.to_a.delete_if {| obj | obj.last_updated == nil}.sort_by {| obj | obj.last_updated.to_date }.reverse %>

<% wday_array = [[],[],[],[],[],[],[]] %>

<% bgms.each do | bgm | %>
  <% wday_array[bgm.last_updated.to_date.wday].push(bgm) %>
<% end %>

<% wday_array.each_with_index do | wday_bgm, idx | %>
  <% unless wday_bgm.length == 0 %>
    <div class="row">
      <blockquote>
        <h3><%= fa_icon "info-circle" %> <%= Date::DAYNAMES[idx] %></h3>
      </blockquote>
    </div>
    <div class="row">
      <% wday_bgm.each do | bgm | %>
        <div class="col-xs-12 col-sm-3">
          <%= render partial: 'card', locals: {item: bgm} %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/cron_task/index.html.erb
<%= @tasks %>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Cron</th>
      <th>Status</th>
      <th>Queue</th>
      <th>Last Enqueue</th>
      <th>Message</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do | task | %>
  <tr>
    <td><%= task.name %></td>
    <td><span class="label label-primary", style="font-family:monospace"><%= task.cron %></span></td>
    <td><%= task.status %></td>
    <td><%= task.queue_name_with_prefix %></td>
    <td><%= task.last_enqueue_time %></td>
    <td><%= task.message %></td>
    <td>
      <%= link_to fa_icon('plug'), cron_task_enqueue_path(task.name), class: "btn btn-danger" %>
      <% if task.status == 'enabled' %>
      <%= link_to fa_icon('pause'), cron_task_toggle_path(task.name), class: "btn btn-warning" %>
      <% else %>
      <%= link_to fa_icon('play'), cron_task_toggle_path(task.name), class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table> 

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, class: 'form-horizontal') do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <%= form.label :name, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
      <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :url, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.text_field :url, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :cover, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.file_field :cover, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :offset, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.number_field :offset, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :is_finished, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.check_box :is_finished, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :total_ep_count, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.number_field :total_ep_count, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :auto_finish, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= form.check_box :auto_finish, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit "Confirm", class: 'btn btn-info' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Panel primary</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', feed: @feed %>
  </div>
</div>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<%= link_to (fa_icon "plus"), new_feed_path, class: 'btn btn-primary' %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url.truncate(15) %></td>
        <td>
          <div class="progress">
            <div class="progress-bar progress-bar-info" style="width: <%= "#{(feed.amount.to_f / feed.total_ep_count.to_f)*100.0}%" %>"></div>
          </div>
        </td>
        <td>
          <%= link_to (fa_icon "check"), feed, class: 'btn btn-info' %>
          <%= link_to (fa_icon "edit"), edit_feed_path(feed), class: 'btn btn-warning' %>
          <%= link_to (fa_icon "trash"), feed, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feeds/new.html.erb
<p><%= link_to (fa_icon "arrow-left"), feeds_path, class: 'btn btn-primary' %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Add New RSS Subscription</h3>
  </div>
  <div class="panel-body">
    <%= render 'form', feed: @feed %>
  </div>
</div>

app/views/feeds/show.html.erb
<div class="panel panel-info row">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @feed.name %></h3>
  </div>
  <div class="panel-body">
    <div class="well well-sm">
      <p class="text-success"><%= @feed.url %></p>
    </div>
    <ul class="list-group col-md-8 col-xs-12">
      <% @feed.items.each do | item | %>
      <li class="list-group-item">
        <span class="badge"><%= item.status %></span>
        <%= item.name %>
        <%= link_to (fa_icon "play"), bangumi_play_path(item), class: 'btn btn-success btn-sm'%>
        <%= link_to (fa_icon "check"), item, class: 'btn btn-primary btn-sm' %>
        <%= link_to (fa_icon "edit"), edit_item_path(item), class: 'btn btn-warning btn-sm' %>
        <%= link_to (fa_icon "trash"), item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      </li>
      <% end %>
    </ul>
    <div class="col-xs-12 col-md-4">
      <%= link_to (fa_icon "arrow-left"), feeds_path, class: 'btn btn-primary' %>
      <%= link_to (fa_icon "edit"), edit_feed_path(@feed), class: 'btn btn-warning' %>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, class: 'form-horizontal') do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  </fieldset>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.status %></td>
        <td><%= item.feed.name %></td>
        <td><%= link_to 'Play', "//bgm.imi.moe/?name=#{item.id}"%></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<%= @item.inspect %>
<!--<%= @status %>-->
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_footer.html.erb
<div class="well">
  <span>
    Commit: <%= link_to APP_Version, "https://github.com/imi415/BGM.RSS/commit/#{APP_Version}" %> /
    System: <%= RUBY_PLATFORM %> /
    Ruby: <%= RUBY_VERSION %> rev.<%= RUBY_REVISION %> /
    Rails: <%= Rails::VERSION::STRING %> /
    Client: <%= request.remote_ip %>
  </span>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "#{fa_icon "times"}No vid you say..".html_safe, root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	<li class="<%= if current_page?(bangumi_index_path) then 'active' end %>"><%= link_to (fa_icon "film"), bangumi_index_path %></li>
	<li class="<%= if current_page?(bangumi_timeline_path) then 'active' end %>"><%= link_to (fa_icon "calendar-check-o"), bangumi_timeline_path %></li>
        <li class="<%= if current_page?(feeds_path) then 'active' end %>"><%= link_to (fa_icon "rss"), feeds_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search" method="post">
        <div class="form-group">
          <input type="text" class="form-control" disabled="" placeholder="Not now...">
        </div>
        <button type="submit" class="btn btn-default disabled"><%= (fa_icon "search") %></button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="disabled"><a href="#"><%= fa_icon "sign-in" %> Let there be login.</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BGMRss</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>